development:
  :adapter: mysql
  :host: localhost
  :username: root
  :password: password
  :database: shopping_cart_development

test:
  :adapter: mysql
  :host: localhost
  :username: root
  :password: password
  :database: shopping_cart_test  

production:
  :adapter: mysql
  :host: localhost
  :username: root
  :password: password
  :database: shopping_cart